# So I basically used P@: mkpasswd --method=sha-512 
---
- name: Set root password
  hosts: ubuntu_servers
  become: yes
  tasks:
    - name: Set the root password to "P@"
      ansible.builtin.user:
        name: root
        password: "$6$UVYbHkg4yHktoRUw$LojNXRfWjvQSNcb7fpWcXfpwewl2TEo7lLSmK0uPCLopdmczp0ctI0NVt5BLIZsnM3OPgnoh26rn2aCSugInU0"

